"""web play queue

Revision ID: 731a0e7c1d6a
Revises: 0f8cd4c61db9
Create Date: 2026-09-28 01:04:23.418252
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "731a0e7c1d6a"
down_revision: str | None = "0f8cd4c61db9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_play_queue",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("song_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("original_order", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("current_index", sa.Integer(), nullable=False),
        sa.Column("position_ms", sa.BigInteger(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_web_play_queue_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_web_play_queue")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("web_play_queue")
    # ### end Alembic commands ###
