"""play queue current index

Revision ID: 6d1bc6554fdf
Revises: ed941e22b515
Create Date: 2026-09-28 09:53:33.156245
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6d1bc6554fdf"
down_revision: str | None = "ed941e22b515"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("play_queue", sa.Column("current_index", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("play_queue", "current_index")
    # ### end Alembic commands ###
