"""web sessions and scan progress

Revision ID: baf34c15bc89
Revises: 2a58e05135ff
Create Date: 2026-09-27 19:24:42.642743
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "baf34c15bc89"
down_revision: str | None = "2a58e05135ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_session",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_web_session_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_web_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_web_session_token_hash")),
    )
    op.create_index(op.f("ix_web_session_user_id"), "web_session", ["user_id"], unique=False)
    op.add_column(
        "scan", sa.Column("phase", sa.Text(), server_default=sa.text("'starting'"), nullable=False)
    )
    op.add_column(
        "scan",
        sa.Column("files_to_read", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "scan", sa.Column("files_read", sa.Integer(), server_default=sa.text("0"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scan", "files_read")
    op.drop_column("scan", "files_to_read")
    op.drop_column("scan", "phase")
    op.drop_index(op.f("ix_web_session_user_id"), table_name="web_session")
    op.drop_table("web_session")
    # ### end Alembic commands ###
