"""bookmark source

Revision ID: 80fae0cbfac9
Revises: 56f632786bfc
Create Date: 2026-10-01 14:51:55.430337
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "80fae0cbfac9"
down_revision: str | None = "56f632786bfc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookmark", sa.Column("source", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookmark", "source")
    # ### end Alembic commands ###
