"""import job kind

Revision ID: dc6f6997d0fd
Revises: 731a0e7c1d6a
Create Date: 2026-09-28 01:31:14.890273
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dc6f6997d0fd"
down_revision: str | None = "731a0e7c1d6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "import_job",
        sa.Column("kind", sa.Text(), server_default=sa.text("'import'"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import_job", "kind")
    # ### end Alembic commands ###
