"""artist info

Revision ID: ed941e22b515
Revises: dc6f6997d0fd
Create Date: 2026-09-28 02:03:48.190921
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ed941e22b515"
down_revision: str | None = "dc6f6997d0fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artist_info",
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column("lastfm_url", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("biography", sa.Text(), nullable=True),
        sa.Column("similar", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("top_tracks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("info_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("info_error", sa.Text(), nullable=True),
        sa.Column("picture_source", sa.Text(), nullable=True),
        sa.Column("picture_page_url", sa.Text(), nullable=True),
        sa.Column("picture_content_type", sa.Text(), nullable=True),
        sa.Column("picture_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("picture_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
            name=op.f("fk_artist_info_artist_id_artist"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("artist_id", name=op.f("pk_artist_info")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artist_info")
    # ### end Alembic commands ###
