"""initial schema

Revision ID: 2a58e05135ff
Revises:
Create Date: 2026-09-27 16:35:19.377318
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2a58e05135ff"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Trigram indexes (search) and accent-insensitive matching.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_enc", sa.LargeBinary(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("max_bit_rate", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "scrobbling_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("settings_role", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("download_role", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("upload_role", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("playlist_role", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("cover_art_role", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("comment_role", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("podcast_role", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("stream_role", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("jukebox_role", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("share_role", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "video_conversion_role", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("avatar_path", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("username", name=op.f("uq_app_user_username")),
    )
    op.create_table(
        "genre",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_genre")),
        sa.UniqueConstraint("name", name=op.f("uq_genre_name")),
    )
    op.create_table(
        "music_folder",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_music_folder")),
        sa.UniqueConstraint("path", name=op.f("uq_music_folder_path")),
    )
    op.create_table(
        "scan",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("files_seen", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("added", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("removed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan")),
    )
    op.create_table(
        "server_setting",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_server_setting")),
    )
    op.create_table(
        "api_key",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_api_key_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_key")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_key_key_hash")),
    )
    op.create_index(op.f("ix_api_key_user_id"), "api_key", ["user_id"], unique=False)
    op.create_table(
        "artwork",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("music_folder_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("mtime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["music_folder_id"],
            ["music_folder.id"],
            name=op.f("fk_artwork_music_folder_id_music_folder"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artwork")),
        sa.UniqueConstraint(
            "music_folder_id", "source", "path", name=op.f("uq_artwork_music_folder_id_source_path")
        ),
    )
    op.create_table(
        "playlist",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("song_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["app_user.id"],
            name=op.f("fk_playlist_owner_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist")),
    )
    op.create_index(op.f("ix_playlist_owner_id"), "playlist", ["owner_id"], unique=False)
    op.create_table(
        "user_music_folder",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("music_folder_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["music_folder_id"],
            ["music_folder.id"],
            name=op.f("fk_user_music_folder_music_folder_id_music_folder"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_user_music_folder_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "music_folder_id", name=op.f("pk_user_music_folder")),
    )
    op.create_table(
        "artist",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("match_key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sort_name", sa.Text(), nullable=False),
        sa.Column("name_search", sa.Text(), nullable=False),
        sa.Column("mbz_artist_id", sa.Text(), nullable=True),
        sa.Column("artwork_id", sa.UUID(), nullable=True),
        sa.Column("album_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("missing_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artwork.id"],
            name=op.f("fk_artist_artwork_id_artwork"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artist")),
        sa.UniqueConstraint("match_key", name=op.f("uq_artist_match_key")),
    )
    op.create_index(
        "ix_artist_name_search_trgm",
        "artist",
        ["name_search"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name_search": "gin_trgm_ops"},
    )
    op.create_table(
        "directory",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("music_folder_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("artwork_id", sa.UUID(), nullable=True),
        sa.Column("mtime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("missing_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artwork.id"],
            name=op.f("fk_directory_artwork_id_artwork"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["music_folder_id"],
            ["music_folder.id"],
            name=op.f("fk_directory_music_folder_id_music_folder"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["directory.id"],
            name=op.f("fk_directory_parent_id_directory"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_directory")),
        sa.UniqueConstraint(
            "music_folder_id", "path", name=op.f("uq_directory_music_folder_id_path")
        ),
    )
    op.create_index(op.f("ix_directory_parent_id"), "directory", ["parent_id"], unique=False)
    op.create_table(
        "playlist_allowed_user",
        sa.Column("playlist_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist.id"],
            name=op.f("fk_playlist_allowed_user_playlist_id_playlist"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_playlist_allowed_user_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("playlist_id", "user_id", name=op.f("pk_playlist_allowed_user")),
    )
    op.create_table(
        "album",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("match_key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sort_name", sa.Text(), nullable=False),
        sa.Column("name_search", sa.Text(), nullable=False),
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column("display_artist", sa.Text(), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=True),
        sa.Column("release_date", sa.Text(), nullable=True),
        sa.Column("original_release_date", sa.Text(), nullable=True),
        sa.Column("is_compilation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "release_types",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "record_labels",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "moods", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("explicit_status", sa.Text(), nullable=True),
        sa.Column(
            "disc_titles",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("mbz_album_id", sa.Text(), nullable=True),
        sa.Column("mbz_release_group_id", sa.Text(), nullable=True),
        sa.Column("artwork_id", sa.UUID(), nullable=True),
        sa.Column("song_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("missing_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"], ["artist.id"], name=op.f("fk_album_artist_id_artist")
        ),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artwork.id"],
            name=op.f("fk_album_artwork_id_artwork"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_album")),
        sa.UniqueConstraint("match_key", name=op.f("uq_album_match_key")),
    )
    op.create_index(op.f("ix_album_artist_id"), "album", ["artist_id"], unique=False)
    op.create_index(
        "ix_album_name_search_trgm",
        "album",
        ["name_search"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name_search": "gin_trgm_ops"},
    )
    op.create_table(
        "artist_annotation",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("starred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("play_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["artist.id"],
            name=op.f("fk_artist_annotation_item_id_artist"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_artist_annotation_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "item_id", name=op.f("pk_artist_annotation")),
    )
    op.create_index(
        op.f("ix_artist_annotation_item_id"), "artist_annotation", ["item_id"], unique=False
    )
    op.create_table(
        "directory_annotation",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("starred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("play_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["directory.id"],
            name=op.f("fk_directory_annotation_item_id_directory"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_directory_annotation_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "item_id", name=op.f("pk_directory_annotation")),
    )
    op.create_index(
        op.f("ix_directory_annotation_item_id"), "directory_annotation", ["item_id"], unique=False
    )
    op.create_table(
        "album_annotation",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("starred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("play_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["album.id"],
            name=op.f("fk_album_annotation_item_id_album"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_album_annotation_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "item_id", name=op.f("pk_album_annotation")),
    )
    op.create_index(
        op.f("ix_album_annotation_item_id"), "album_annotation", ["item_id"], unique=False
    )
    op.create_table(
        "album_artist",
        sa.Column("album_id", sa.UUID(), nullable=False),
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("position", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["album.id"],
            name=op.f("fk_album_artist_album_id_album"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
            name=op.f("fk_album_artist_artist_id_artist"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("album_id", "artist_id", "role", name=op.f("pk_album_artist")),
    )
    op.create_index(op.f("ix_album_artist_artist_id"), "album_artist", ["artist_id"], unique=False)
    op.create_table(
        "album_genre",
        sa.Column("album_id", sa.UUID(), nullable=False),
        sa.Column("genre_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["album.id"],
            name=op.f("fk_album_genre_album_id_album"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genre.id"],
            name=op.f("fk_album_genre_genre_id_genre"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("album_id", "genre_id", name=op.f("pk_album_genre")),
    )
    op.create_index(op.f("ix_album_genre_genre_id"), "album_genre", ["genre_id"], unique=False)
    op.create_table(
        "song",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("music_folder_id", sa.Integer(), nullable=False),
        sa.Column("directory_id", sa.UUID(), nullable=False),
        sa.Column("album_id", sa.UUID(), nullable=False),
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("sort_title", sa.Text(), nullable=False),
        sa.Column("title_search", sa.Text(), nullable=False),
        sa.Column("display_artist", sa.Text(), nullable=False),
        sa.Column("display_composer", sa.Text(), nullable=True),
        sa.Column("track_number", sa.SmallInteger(), nullable=True),
        sa.Column("disc_number", sa.SmallInteger(), nullable=True),
        sa.Column("year", sa.SmallInteger(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("bit_rate", sa.Integer(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("bit_depth", sa.SmallInteger(), nullable=True),
        sa.Column("channels", sa.SmallInteger(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("suffix", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("bpm", sa.SmallInteger(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("explicit_status", sa.Text(), nullable=True),
        sa.Column("replaygain_track_gain", sa.REAL(), nullable=True),
        sa.Column("replaygain_track_peak", sa.REAL(), nullable=True),
        sa.Column("replaygain_album_gain", sa.REAL(), nullable=True),
        sa.Column("replaygain_album_peak", sa.REAL(), nullable=True),
        sa.Column("mbz_recording_id", sa.Text(), nullable=True),
        sa.Column("mbz_track_id", sa.Text(), nullable=True),
        sa.Column("artwork_id", sa.UUID(), nullable=True),
        sa.Column("file_mtime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("missing_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["album_id"], ["album.id"], name=op.f("fk_song_album_id_album")),
        sa.ForeignKeyConstraint(
            ["artist_id"], ["artist.id"], name=op.f("fk_song_artist_id_artist")
        ),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artwork.id"],
            name=op.f("fk_song_artwork_id_artwork"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["directory_id"],
            ["directory.id"],
            name=op.f("fk_song_directory_id_directory"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["music_folder_id"],
            ["music_folder.id"],
            name=op.f("fk_song_music_folder_id_music_folder"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_song")),
        sa.UniqueConstraint("music_folder_id", "path", name=op.f("uq_song_music_folder_id_path")),
    )
    op.create_index(
        "ix_song_album_order", "song", ["album_id", "disc_number", "track_number"], unique=False
    )
    op.create_index(op.f("ix_song_artist_id"), "song", ["artist_id"], unique=False)
    op.create_index(op.f("ix_song_directory_id"), "song", ["directory_id"], unique=False)
    op.create_index(
        "ix_song_title_search_trgm",
        "song",
        ["title_search"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_search": "gin_trgm_ops"},
    )
    op.create_table(
        "bookmark",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("position_ms", sa.BigInteger(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["song.id"], name=op.f("fk_bookmark_song_id_song"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_bookmark_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "song_id", name=op.f("pk_bookmark")),
    )
    op.create_table(
        "lyrics",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("lang", sa.Text(), server_default=sa.text("'xxx'"), nullable=False),
        sa.Column("synced", sa.Boolean(), nullable=False),
        sa.Column("offset_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["song.id"], name=op.f("fk_lyrics_song_id_song"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lyrics")),
    )
    op.create_index(op.f("ix_lyrics_song_id"), "lyrics", ["song_id"], unique=False)
    op.create_table(
        "now_playing",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("client", sa.Text(), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["song.id"], name=op.f("fk_now_playing_song_id_song"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_now_playing_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "client", name=op.f("pk_now_playing")),
    )
    op.create_table(
        "play_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("client", sa.Text(), nullable=False),
        sa.Column("submission", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"], ["song.id"], name=op.f("fk_play_history_song_id_song"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_play_history_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_play_history")),
    )
    op.create_index(op.f("ix_play_history_song_id"), "play_history", ["song_id"], unique=False)
    op.create_index(
        "ix_play_history_user_played", "play_history", ["user_id", "played_at"], unique=False
    )
    op.create_table(
        "play_queue",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("current_song_id", sa.UUID(), nullable=True),
        sa.Column("position_ms", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("changed_by", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_song_id"],
            ["song.id"],
            name=op.f("fk_play_queue_current_song_id_song"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_play_queue_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_play_queue")),
    )
    op.create_table(
        "playlist_entry",
        sa.Column("playlist_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist.id"],
            name=op.f("fk_playlist_entry_playlist_id_playlist"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
            name=op.f("fk_playlist_entry_song_id_song"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("playlist_id", "position", name=op.f("pk_playlist_entry")),
    )
    op.create_index(op.f("ix_playlist_entry_song_id"), "playlist_entry", ["song_id"], unique=False)
    op.create_table(
        "song_annotation",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("starred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("play_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["song.id"],
            name=op.f("fk_song_annotation_item_id_song"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_song_annotation_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "item_id", name=op.f("pk_song_annotation")),
    )
    op.create_index(
        op.f("ix_song_annotation_item_id"), "song_annotation", ["item_id"], unique=False
    )
    op.create_table(
        "song_artist",
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("sub_role", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("position", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
            name=op.f("fk_song_artist_artist_id_artist"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["song.id"], name=op.f("fk_song_artist_song_id_song"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "song_id", "artist_id", "role", "sub_role", name=op.f("pk_song_artist")
        ),
    )
    op.create_index(op.f("ix_song_artist_artist_id"), "song_artist", ["artist_id"], unique=False)
    op.create_table(
        "song_genre",
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("genre_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genre.id"],
            name=op.f("fk_song_genre_genre_id_genre"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["song.id"], name=op.f("fk_song_genre_song_id_song"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("song_id", "genre_id", name=op.f("pk_song_genre")),
    )
    op.create_index(op.f("ix_song_genre_genre_id"), "song_genre", ["genre_id"], unique=False)
    op.create_table(
        "play_queue_entry",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
            name=op.f("fk_play_queue_entry_song_id_song"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["play_queue.user_id"],
            name=op.f("fk_play_queue_entry_user_id_play_queue"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "position", name=op.f("pk_play_queue_entry")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("play_queue_entry")
    op.drop_index(op.f("ix_song_genre_genre_id"), table_name="song_genre")
    op.drop_table("song_genre")
    op.drop_index(op.f("ix_song_artist_artist_id"), table_name="song_artist")
    op.drop_table("song_artist")
    op.drop_index(op.f("ix_song_annotation_item_id"), table_name="song_annotation")
    op.drop_table("song_annotation")
    op.drop_index(op.f("ix_playlist_entry_song_id"), table_name="playlist_entry")
    op.drop_table("playlist_entry")
    op.drop_table("play_queue")
    op.drop_index("ix_play_history_user_played", table_name="play_history")
    op.drop_index(op.f("ix_play_history_song_id"), table_name="play_history")
    op.drop_table("play_history")
    op.drop_table("now_playing")
    op.drop_index(op.f("ix_lyrics_song_id"), table_name="lyrics")
    op.drop_table("lyrics")
    op.drop_table("bookmark")
    op.drop_index(
        "ix_song_title_search_trgm",
        table_name="song",
        postgresql_using="gin",
        postgresql_ops={"title_search": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_song_directory_id"), table_name="song")
    op.drop_index(op.f("ix_song_artist_id"), table_name="song")
    op.drop_index("ix_song_album_order", table_name="song")
    op.drop_table("song")
    op.drop_index(op.f("ix_album_genre_genre_id"), table_name="album_genre")
    op.drop_table("album_genre")
    op.drop_index(op.f("ix_album_artist_artist_id"), table_name="album_artist")
    op.drop_table("album_artist")
    op.drop_index(op.f("ix_album_annotation_item_id"), table_name="album_annotation")
    op.drop_table("album_annotation")
    op.drop_index(op.f("ix_directory_annotation_item_id"), table_name="directory_annotation")
    op.drop_table("directory_annotation")
    op.drop_index(op.f("ix_artist_annotation_item_id"), table_name="artist_annotation")
    op.drop_table("artist_annotation")
    op.drop_index(
        "ix_album_name_search_trgm",
        table_name="album",
        postgresql_using="gin",
        postgresql_ops={"name_search": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_album_artist_id"), table_name="album")
    op.drop_table("album")
    op.drop_table("playlist_allowed_user")
    op.drop_index(op.f("ix_directory_parent_id"), table_name="directory")
    op.drop_table("directory")
    op.drop_index(
        "ix_artist_name_search_trgm",
        table_name="artist",
        postgresql_using="gin",
        postgresql_ops={"name_search": "gin_trgm_ops"},
    )
    op.drop_table("artist")
    op.drop_table("user_music_folder")
    op.drop_index(op.f("ix_playlist_owner_id"), table_name="playlist")
    op.drop_table("playlist")
    op.drop_table("artwork")
    op.drop_index(op.f("ix_api_key_user_id"), table_name="api_key")
    op.drop_table("api_key")
    op.drop_table("server_setting")
    op.drop_table("scan")
    op.drop_table("music_folder")
    op.drop_table("genre")
    op.drop_table("app_user")
    # ### end Alembic commands ###
