"""web players

Revision ID: 56f632786bfc
Revises: 2c8e6f1b4d97
Create Date: 2026-09-30 16:24:46.677633
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "56f632786bfc"
down_revision: str | None = "2c8e6f1b4d97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_player",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("song_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("original_order", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("current_index", sa.Integer(), nullable=False),
        sa.Column("position_ms", sa.BigInteger(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_web_player_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_web_player")),
    )
    op.create_index(
        "uq_web_player_user_id_name",
        "web_player",
        ["user_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_web_player_user_id_name", table_name="web_player")
    op.drop_table("web_player")
    # ### end Alembic commands ###
